'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { BLOG_CATEGORIES, escapeHtml, parseFrontmatter, readingTime, slugify } = require('./blog-utils');
const { markdownToHtml } = require('./markdown');

const root = path.resolve(__dirname, '..');
const contentDir = path.join(root, 'content', 'blog');
const templatesDir = path.join(root, 'templates');
const outputDir = path.join(root, 'blog');
const tempDir = path.join(root, '.blog-build-tmp');
const markerName = '.generated-by-build-blog';
const allowedCategories = new Set(BLOG_CATEGORIES);

function assertDirectChild(target) {
  if (path.dirname(path.resolve(target)) !== root) {
    throw new Error(`Refusing to replace a path outside the project root: ${target}`);
  }
}

function formatDate(value) {
  return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', timeZone: 'UTC' })
    .format(new Date(`${value}T00:00:00Z`));
}

function formatMonth(value) {
  return new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' })
    .format(new Date(`${value}T00:00:00Z`));
}

function renderTemplate(template, values) {
  let output = template;
  Object.entries(values).forEach(([key, value]) => {
    output = output.replaceAll(`{{${key}}}`, String(value));
  });
  const unresolved = output.match(/{{[A-Z_]+}}/g);
  if (unresolved) throw new Error(`Unresolved template values: ${[...new Set(unresolved)].join(', ')}`);
  return output;
}

function adjacentLink(label, post, className) {
  if (!post) return '';
  return `<a class="adjacent-post ${className}" href="../../blog/${escapeHtml(post.slug)}/index.html"><span class="meta">${label}</span>${escapeHtml(post.title)}</a>`;
}

if (!fs.existsSync(contentDir)) throw new Error('content/blog/ does not exist. Run node scripts/migrate-blogs.js first.');
const articleTemplate = fs.readFileSync(path.join(templatesDir, 'blog-post.html'), 'utf8');
const indexTemplate = fs.readFileSync(path.join(templatesDir, 'blog-index.html'), 'utf8');

const posts = fs.readdirSync(contentDir)
  .filter((name) => name.endsWith('.md'))
  .map((filename) => {
    const parsed = parseFrontmatter(fs.readFileSync(path.join(contentDir, filename), 'utf8'), filename);
    const { title, date, category, summary } = parsed.data;
    if (!title || !date || !category || !summary) throw new Error(`${filename}: title, date, category and summary are required.`);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(Date.parse(`${date}T00:00:00Z`))) throw new Error(`${filename}: invalid date ${date}.`);
    if (!allowedCategories.has(category)) throw new Error(`${filename}: category must be Homelab, Projects or Web.`);
    const filenameSlug = filename.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, '');
    const slug = parsed.data.slug ? slugify(parsed.data.slug) : filenameSlug;
    return { filename, title, date, category, summary, slug, body: parsed.body, readingTime: readingTime(parsed.body) };
  })
  .sort((a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title));

if (!posts.length) throw new Error('No Markdown posts found in content/blog/.');
const duplicate = posts.find((post, index) => posts.findIndex((candidate) => candidate.slug === post.slug) !== index);
if (duplicate) throw new Error(`Duplicate blog slug: ${duplicate.slug}.`);

assertDirectChild(tempDir);
assertDirectChild(outputDir);
fs.rmSync(tempDir, { recursive: true, force: true });
fs.mkdirSync(tempDir, { recursive: true });
fs.writeFileSync(path.join(tempDir, markerName), 'Generated by scripts/build-blog.js. Do not edit files in blog/ directly.\n');

posts.forEach((post, index) => {
  const older = posts[index + 1];
  const newer = posts[index - 1];
  const prevQuick = older
    ? `<a class="quicknav-prev" href="../../blog/${escapeHtml(older.slug)}/index.html" rel="prev" title="${escapeHtml(older.title)}">&lt; previous</a>`
    : `<span class="quicknav-empty" aria-hidden="true">&lt; previous</span>`;
  const nextQuick = newer
    ? `<a class="quicknav-next" href="../../blog/${escapeHtml(newer.slug)}/index.html" rel="next" title="${escapeHtml(newer.title)}">next &gt;</a>`
    : `<span class="quicknav-empty" aria-hidden="true">next &gt;</span>`;

  const article = renderTemplate(articleTemplate, {
    TITLE: escapeHtml(post.title),
    DESCRIPTION: escapeHtml(post.summary),
    CATEGORY: escapeHtml(post.category),
    CATEGORY_KEY: post.category.toLowerCase(),
    DATE: post.date,
    DATE_FORMATTED: formatDate(post.date),
    READING_TIME: post.readingTime,
    ARTICLE_HTML: markdownToHtml(post.body),
    ADJACENT_NAV: `${adjacentLink('Older', older, 'older-post')}${adjacentLink('Newer', newer, 'newer-post')}`,
    PREVIOUS_POST_QUICK: prevQuick,
    NEXT_POST_QUICK: nextQuick
  });
  const destination = path.join(tempDir, post.slug);
  fs.mkdirSync(destination, { recursive: true });
  fs.writeFileSync(path.join(destination, 'index.html'), article, 'utf8');
});

let activeMonth = '';
const archive = [];
const monthNav = [];
const categoryCounts = { Homelab: 0, Projects: 0, Web: 0 };
const monthCounts = new Map();
posts.forEach((post) => {
  categoryCounts[post.category] += 1;
  const month = post.date.slice(0, 7);
  monthCounts.set(month, (monthCounts.get(month) || 0) + 1);
});
posts.forEach((post, index) => {
  const month = post.date.slice(0, 7);
  if (month !== activeMonth) {
    activeMonth = month;
    const monthLabel = escapeHtml(formatMonth(post.date));
    const monthCount = monthCounts.get(month);
    archive.push(`<li class="archive-month" data-archive-month="${month}"><h2 id="month-${month}">${monthLabel} <span>${monthCount} ${monthCount === 1 ? 'entry' : 'entries'}</span></h2></li>`);
    monthNav.push(`<a href="#month-${month}" data-month-link="${month}" aria-label="${monthLabel}, ${monthCount} ${monthCount === 1 ? 'post' : 'posts'}">${monthLabel} <span aria-hidden="true">${monthCount}</span></a>`);
  }
  archive.push(`<li class="post-entry" data-post-category="${post.category.toLowerCase()}" data-post-month="${month}" data-lattice-target="${index}">
          <p class="post-date meta"><time datetime="${post.date}">${escapeHtml(formatDate(post.date))}</time></p>
          <article class="post-copy"><h3><a href="./${escapeHtml(post.slug)}/index.html">${escapeHtml(post.title)}</a></h3><p class="post-summary">${escapeHtml(post.summary)}</p></article>
          <p class="post-facts meta"><span>${escapeHtml(post.category)}</span><span>${post.readingTime} min read</span></p>
        </li>`);
});

const indexHtml = renderTemplate(indexTemplate, {
  POSTS: archive.join('\n        '),
  MONTH_NAV: monthNav.join('\n          '),
  POST_COUNT: posts.length,
  HOMELAB_COUNT: categoryCounts.Homelab,
  PROJECTS_COUNT: categoryCounts.Projects,
  WEB_COUNT: categoryCounts.Web
});
fs.writeFileSync(path.join(tempDir, 'index.html'), indexHtml, 'utf8');

if (fs.existsSync(outputDir)) {
  if (!fs.existsSync(path.join(outputDir, markerName))) {
    throw new Error('Refusing to replace blog/: it is not marked as generated output.');
  }
  fs.rmSync(outputDir, { recursive: true, force: false });
}
fs.renameSync(tempDir, outputDir);

// Sync featured blog post metadata and title on index.html
const indexHtmlPath = path.join(root, 'index.html');
if (fs.existsSync(indexHtmlPath)) {
  let indexContent = fs.readFileSync(indexHtmlPath, 'utf8');
  const featureRegex = /(<article class="region blog-feature" id="blog">[\s\S]*?<p class="meta">)([\s\S]*?)(<\/p>[\s\S]*?<h3><a href="blog\/([^"/]+)\/index\.html">)([\s\S]*?)(<\/a><\/h3>[\s\S]*?<\/article>)/;
  const match = featureRegex.exec(indexContent);
  if (match) {
    const slug = match[4];
    const post = posts.find((p) => p.slug === slug);
    if (post) {
      const metaContent = `Blog · Selected post<br>${post.date} · ${post.readingTime} min read`;
      const titleContent = escapeHtml(post.title);
      indexContent = indexContent.replace(featureRegex, `$1${metaContent}$3${titleContent}$6`);
      fs.writeFileSync(indexHtmlPath, indexContent, 'utf8');
      console.log(`Synchronized featured post on index.html: "${post.title}" (${post.date}, ${post.readingTime} min read).`);
    }
  }
}

console.log(`Built blog/index.html and ${posts.length} article routes.`);
